Made config loading compatible with Python 3.12
velebit-ai/useful pull request #2
Opened 2024-10-17 14:29 UTC by ssopar

Fix for loading config with Python 3.12.

2024-10-17 14:35 UTC, tlevani requested changes

2024-10-17 14:35 UTC, tlevani commented on setup.py
>          "Programming Language :: Python :: 3.7"
obriši ove dvije linije. to ne supportamo

2024-10-17 14:35 UTC, tlevani commented on useful/creator/_creators.py
> +    return (isinstance(x, collections.abc.Iterable) and
jel ovo testirano da radi na svim verzijama izmedju 3.8 i 3.12?

2024-10-23 13:37 UTC, ssopar commented on useful/creator/_creators.py
> +    return (isinstance(x, collections.abc.Iterable) and
sad je, radi

2024-10-23 14:32 UTC, tlevani commented
ono što još fali je update verzije. negdje postoji fajl __version__.py ili tako nesto, i treba se bumpat zadnji broj verzije za 1

2024-10-24 22:41 UTC, tlevani approved these changes

2024-10-25 09:18 UTC, merged